services:
  backend:
    build: .
    container_name: chocorocks_backend_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/chocorocks_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: ${MAIL_USERNAME:-MailUsername}
      MAIL_PASSWORD: ${MAIL_PASSWORD:-MailPassword}

      COMPANY_NAME: ${COMPANY_NAME:-Chocorocks}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL:-soporte@chocorocks.com}

      SUPABASE_URL: ${SUPABASE_URL:-SupabaseURL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY:-SupabaseAnonKey}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET:-Secret}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqeGtyenZvd3VicnNscHh0bnVoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzgyOTQ1MSwiZXhwIjoyMDY5NDA1NDUxfQ.8O3otV82qf5yDAW4wBOuK2kza_qL91TZYdtaUOXyoFw}

    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: chocorocks_backend_postgres
    environment:
      POSTGRES_DB: chocorocks_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
