spring:
  application:
    name: chocorocks-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:MailUsername}
    password: ${MAIL_PASSWORD:MailPassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 8000
          connectiontimeout: 8000
          writetimeout: 8000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SUPABASE_URL:SupabaseURL}/auth/v1

supabase:
  url: ${SUPABASE_URL:SupabaseURL}
  anon:
    key: ${SUPABASE_ANON_KEY:AnonKey}
  jwt:
    secret: ${SUPABASE_JWT_SECRET:Secret}
  service:
    key: ${SUPABASE_SERVICE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqeGtyenZvd3VicnNscHh0bnVoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzgyOTQ1MSwiZXhwIjoyMDY5NDA1NDUxfQ.8O3otV82qf5yDAW4wBOuK2kza_qL91TZYdtaUOXyoFw}

app:
  company:
    name: ${COMPANY_NAME:Chocorocks}
    support-email: ${SUPPORT_EMAIL:soporte@chocorocks.com}
  xml:
    encoding: UTF-8
    format-output: true
  data:
    seed: ${ENABLE_DATA_SEEDING:false}

logging:
  level:
    com.puce.chocorocks_backend.security: DEBUG
    org.springframework.security: DEBUG